/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Colors: () => import('#controllers/colors_controller'),
  Profile: () => import('#controllers/profile_controller'),
  profile: {
    Totp: () => import('#controllers/profile/totp_controller'),
    Webauthn: () => import('#controllers/profile/webauthn_controller'),
  },
  Session: () => import('#controllers/session_controller'),
  session: {
    ConfirmSecurity: () => import('#controllers/session/confirm_security_controller'),
    Totp: () => import('#controllers/session/totp_controller'),
    TotpRecover: () => import('#controllers/session/totp_recover_controller'),
  },
  SignIn: () => import('#controllers/sign_in_controller'),
  Users: () => import('#controllers/users_controller'),
}
