/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Authors {
  createdAt: Timestamp;
  id: Generated<number>;
  name: string;
  updatedAt: Timestamp;
}

export interface Books {
  authorId: number;
  createdAt: Timestamp;
  id: Generated<number>;
  name: string;
  updatedAt: Timestamp;
}

export interface Users {
  createdAt: Timestamp;
  email: string;
  fullName: string;
  id: Generated<number>;
  password: string;
  updatedAt: Timestamp;
}

export interface DB {
  authors: Authors;
  books: Books;
  users: Users;
}
