// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type UsersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['index'], false>
}
type UsersCreateGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['create'], false>
}
type UsersPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/users_validator.ts')['createUserValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['store'], true>
}
type UsersIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['show'], false>
}
type UsersIdEditGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['edit'], false>
}
type UsersIdPutPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/users_validator.ts')['updateUserValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['update'], true>
}
type UsersIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['destroy'], false>
}
type SignInGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session_controller.ts').default['show'], false>
}
type SigninCheckemailPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session_controller.ts').default['checkEmail'], false>
}
type SignInPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/session_validator.ts')['createSessionValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/session_controller.ts').default['store'], true>
}
type PasswordlessOptionsPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session_controller.ts').default['passwordlessOptions'], false>
}
type PasswordlessVerifyPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session_controller.ts').default['passwordlessVerify'], false>
}
type SessionDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session_controller.ts').default['destroy'], false>
}
type ProfileGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profile_controller.ts').default['show'], false>
}
type ProfileConfirmsecurityOptionsPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profile_controller.ts').default['confirmSecurityOptions'], false>
}
type ProfileConfirmsecurityPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/profile_validator.ts')['confirmSecurityValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/profile_controller.ts').default['confirmSecurity'], true>
}
type ProfileEnablemfaPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profile_controller.ts').default['enable'], false>
}
type ProfilePasskeysIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profile_controller.ts').default['removePasskey'], false>
}
type 2faChallengeGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/two_factor_controller.ts').default['challenge'], false>
}
type 2faTotpVerifyPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/verify_otp.ts')['verifyOtpValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/two_factor_controller.ts').default['verify'], true>
}
type 2faWebauthnAuthenticateOptionsPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/webauthn_controller.ts').default['authenticationOptions'], false>
}
type 2faWebauthnAuthenticateVerifyPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/webauthn_controller.ts').default['verifyAuthentication'], false>
}
type 2faTotpGeneratePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/two_factor_controller.ts').default['generate'], false>
}
type 2faRecoverycodesPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/two_factor_controller.ts').default['generateRecoveryCodes'], false>
}
type 2faDisablePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/two_factor_controller.ts').default['disable'], false>
}
type 2faWebauthnRegisterOptionsPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/webauthn_controller.ts').default['registerOptions'], false>
}
type 2faWebauthnRegisterVerifyPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/webauthn_controller.ts').default['verifyRegistration'], false>
}
type ColorsCssGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/colors_controller.ts').default['handle'], false>
}
export interface ApiDefinition {
  'users': {
    '$url': {
    };
    '$get': UsersGetHead;
    '$head': UsersGetHead;
    'create': {
      '$url': {
      };
      '$get': UsersCreateGetHead;
      '$head': UsersCreateGetHead;
    };
    '$post': UsersPost;
    ':id': {
      '$url': {
      };
      '$get': UsersIdGetHead;
      '$head': UsersIdGetHead;
      'edit': {
        '$url': {
        };
        '$get': UsersIdEditGetHead;
        '$head': UsersIdEditGetHead;
      };
      '$put': UsersIdPutPatch;
      '$patch': UsersIdPutPatch;
      '$delete': UsersIdDelete;
    };
  };
  'sign-in': {
    '$url': {
    };
    '$get': SignInGetHead;
    '$head': SignInGetHead;
    'check-email': {
      '$url': {
      };
      '$post': SigninCheckemailPost;
    };
    '$post': SignInPost;
  };
  'passwordless': {
    'options': {
      '$url': {
      };
      '$post': PasswordlessOptionsPost;
    };
    'verify': {
      '$url': {
      };
      '$post': PasswordlessVerifyPost;
    };
  };
  'session': {
    '$url': {
    };
    '$delete': SessionDelete;
  };
  'profile': {
    '$url': {
    };
    '$get': ProfileGetHead;
    '$head': ProfileGetHead;
    'confirm-security': {
      'options': {
        '$url': {
        };
        '$post': ProfileConfirmsecurityOptionsPost;
      };
      '$url': {
      };
      '$post': ProfileConfirmsecurityPost;
    };
    'enable-mfa': {
      '$url': {
      };
      '$post': ProfileEnablemfaPost;
    };
    'passkeys': {
      ':id': {
        '$url': {
        };
        '$delete': ProfilePasskeysIdDelete;
      };
    };
  };
  '2fa': {
    'challenge': {
      '$url': {
      };
      '$get': 2faChallengeGetHead;
      '$head': 2faChallengeGetHead;
    };
    'totp': {
      'verify': {
        '$url': {
        };
        '$post': 2faTotpVerifyPost;
      };
      'generate': {
        '$url': {
        };
        '$post': 2faTotpGeneratePost;
      };
    };
    'webauthn': {
      'authenticate': {
        'options': {
          '$url': {
          };
          '$post': 2faWebauthnAuthenticateOptionsPost;
        };
        'verify': {
          '$url': {
          };
          '$post': 2faWebauthnAuthenticateVerifyPost;
        };
      };
      'register': {
        'options': {
          '$url': {
          };
          '$post': 2faWebauthnRegisterOptionsPost;
        };
        'verify': {
          '$url': {
          };
          '$post': 2faWebauthnRegisterVerifyPost;
        };
      };
    };
    'recovery-codes': {
      '$url': {
      };
      '$post': 2faRecoverycodesPost;
    };
    'disable': {
      '$url': {
      };
      '$post': 2faDisablePost;
    };
  };
  'colors.css': {
    '$url': {
    };
    '$get': ColorsCssGetHead;
    '$head': ColorsCssGetHead;
  };
}
const routes = [
  {
    params: [],
    name: 'users.index',
    path: '/users',
    method: ["GET","HEAD"],
    types: {} as UsersGetHead,
  },
  {
    params: [],
    name: 'users.create',
    path: '/users/create',
    method: ["GET","HEAD"],
    types: {} as UsersCreateGetHead,
  },
  {
    params: [],
    name: 'users.store',
    path: '/users',
    method: ["POST"],
    types: {} as UsersPost,
  },
  {
    params: ["id"],
    name: 'users.show',
    path: '/users/:id',
    method: ["GET","HEAD"],
    types: {} as UsersIdGetHead,
  },
  {
    params: ["id"],
    name: 'users.edit',
    path: '/users/:id/edit',
    method: ["GET","HEAD"],
    types: {} as UsersIdEditGetHead,
  },
  {
    params: ["id"],
    name: 'users.update',
    path: '/users/:id',
    method: ["PUT","PATCH"],
    types: {} as UsersIdPutPatch,
  },
  {
    params: ["id"],
    name: 'users.destroy',
    path: '/users/:id',
    method: ["DELETE"],
    types: {} as UsersIdDelete,
  },
  {
    params: [],
    name: '2fa.challenge',
    path: '/2fa/challenge',
    method: ["GET","HEAD"],
    types: {} as 2faChallengeGetHead,
  },
  {
    params: [],
    name: '2fa.totp.verify',
    path: '/2fa/totp/verify',
    method: ["POST"],
    types: {} as 2faTotpVerifyPost,
  },
  {
    params: [],
    name: '2fa.webauthn.authenticationOptions',
    path: '/2fa/webauthn/authenticate/options',
    method: ["POST"],
    types: {} as 2faWebauthnAuthenticateOptionsPost,
  },
  {
    params: [],
    name: '2fa.webauthn.verifyAuthentication',
    path: '/2fa/webauthn/authenticate/verify',
    method: ["POST"],
    types: {} as 2faWebauthnAuthenticateVerifyPost,
  },
  {
    params: [],
    name: '2fa.totp.generate',
    path: '/2fa/totp/generate',
    method: ["POST"],
    types: {} as 2faTotpGeneratePost,
  },
  {
    params: [],
    name: '2fa.recovery.generate',
    path: '/2fa/recovery-codes',
    method: ["POST"],
    types: {} as 2faRecoverycodesPost,
  },
  {
    params: [],
    name: '2fa.disable',
    path: '/2fa/disable',
    method: ["POST"],
    types: {} as 2faDisablePost,
  },
  {
    params: [],
    name: '2fa.webauthn.registerOptions',
    path: '/2fa/webauthn/register/options',
    method: ["POST"],
    types: {} as 2faWebauthnRegisterOptionsPost,
  },
  {
    params: [],
    name: '2fa.webauthn.verifyRegistration',
    path: '/2fa/webauthn/register/verify',
    method: ["POST"],
    types: {} as 2faWebauthnRegisterVerifyPost,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
