// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type UsersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['index'], false>
}
type UsersCreateGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['create'], false>
}
type UsersPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/users_validator.ts')['createUserValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['store'], true>
}
type UsersIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['show'], false>
}
type UsersIdEditGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['edit'], false>
}
type UsersIdPutPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/users_validator.ts')['updateUserValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['update'], true>
}
type UsersIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['destroy'], false>
}
type ProfileGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profile_controller.ts').default['show'], false>
}
type ProfileWebauthnOptionsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profile/webauthn_controller.ts').default['options'], false>
}
type ProfileWebauthnPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profile/webauthn_controller.ts').default['store'], false>
}
type ProfileWebauthnIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profile/webauthn_controller.ts').default['destroy'], false>
}
type ProfileTotpPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profile/totp_controller.ts').default['store'], false>
}
type ProfileTotpVerifyPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/totp_validator.ts')['verifyValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/profile/totp_controller.ts').default['verify'], true>
}
type ProfileTotpDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profile/totp_controller.ts').default['destroy'], false>
}
type ProfileTotpRegenerationPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profile/totp_controller.ts').default['regenerateRecoveryCodes'], false>
}
type ProfileConfirmsecurityGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/profile/confirm_security_controller.ts').default['index'], false>
}
type ProfileConfirmsecurityPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/confirm_security_validator.ts')['confirmSecurityValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/profile/confirm_security_controller.ts').default['store'], true>
}
type SessionDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session_controller.ts').default['destroy'], false>
}
type SignInGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session_controller.ts').default['show'], false>
}
type SessionPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/session_validator.ts')['createSessionValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/session_controller.ts').default['store'], true>
}
type SessionOptionsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session/options_controller.ts').default['handle'], false>
}
type SessionWebauthnIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session/webauthn_controller.ts').default['index'], false>
}
type SessionWebauthnIdPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session/webauthn_controller.ts').default['store'], false>
}
type SessionTotpGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session/totp_controller.ts').default['index'], false>
}
type SessionTotpPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/verify_otp.ts')['verifyOtpValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/session/totp_controller.ts').default['store'], true>
}
type SessionTotpRecoverGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session/totp_recover_controller.ts').default['index'], false>
}
type SessionTotpRecoverPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/recover_otp_validator.ts')['recoverOtpValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/session/totp_recover_controller.ts').default['store'], true>
}
type ColorsCssGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/colors_controller.ts').default['handle'], false>
}
export interface ApiDefinition {
  'users': {
    '$url': {
    };
    '$get': UsersGetHead;
    '$head': UsersGetHead;
    'create': {
      '$url': {
      };
      '$get': UsersCreateGetHead;
      '$head': UsersCreateGetHead;
    };
    '$post': UsersPost;
    ':id': {
      '$url': {
      };
      '$get': UsersIdGetHead;
      '$head': UsersIdGetHead;
      'edit': {
        '$url': {
        };
        '$get': UsersIdEditGetHead;
        '$head': UsersIdEditGetHead;
      };
      '$put': UsersIdPutPatch;
      '$patch': UsersIdPutPatch;
      '$delete': UsersIdDelete;
    };
  };
  'profile': {
    '$url': {
    };
    '$get': ProfileGetHead;
    '$head': ProfileGetHead;
    'webauthn': {
      'options': {
        '$url': {
        };
        '$get': ProfileWebauthnOptionsGetHead;
        '$head': ProfileWebauthnOptionsGetHead;
      };
      '$url': {
      };
      '$post': ProfileWebauthnPost;
      ':id': {
        '$url': {
        };
        '$delete': ProfileWebauthnIdDelete;
      };
    };
    'totp': {
      '$url': {
      };
      '$post': ProfileTotpPost;
      'verify': {
        '$url': {
        };
        '$post': ProfileTotpVerifyPost;
      };
      '$delete': ProfileTotpDelete;
      'regeneration': {
        '$url': {
        };
        '$post': ProfileTotpRegenerationPost;
      };
    };
    'confirm-security': {
      '$url': {
      };
      '$get': ProfileConfirmsecurityGetHead;
      '$head': ProfileConfirmsecurityGetHead;
      '$post': ProfileConfirmsecurityPost;
    };
  };
  'session': {
    '$url': {
    };
    '$delete': SessionDelete;
    '$post': SessionPost;
    'options': {
      ':email': {
        '$url': {
        };
        '$get': SessionOptionsIdGetHead;
        '$head': SessionOptionsIdGetHead;
      };
    };
    'webauthn': {
      ':email': {
        '$url': {
        };
        '$get': SessionWebauthnIdGetHead;
        '$head': SessionWebauthnIdGetHead;
        '$post': SessionWebauthnIdPost;
      };
    };
    'totp': {
      '$url': {
      };
      '$get': SessionTotpGetHead;
      '$head': SessionTotpGetHead;
      '$post': SessionTotpPost;
      'recover': {
        '$url': {
        };
        '$get': SessionTotpRecoverGetHead;
        '$head': SessionTotpRecoverGetHead;
        '$post': SessionTotpRecoverPost;
      };
    };
  };
  'sign-in': {
    '$url': {
    };
    '$get': SignInGetHead;
    '$head': SignInGetHead;
  };
  'colors.css': {
    '$url': {
    };
    '$get': ColorsCssGetHead;
    '$head': ColorsCssGetHead;
  };
}
const routes = [
  {
    params: [],
    name: 'users.index',
    path: '/users',
    method: ["GET","HEAD"],
    types: {} as UsersGetHead,
  },
  {
    params: [],
    name: 'users.create',
    path: '/users/create',
    method: ["GET","HEAD"],
    types: {} as UsersCreateGetHead,
  },
  {
    params: [],
    name: 'users.store',
    path: '/users',
    method: ["POST"],
    types: {} as UsersPost,
  },
  {
    params: ["id"],
    name: 'users.show',
    path: '/users/:id',
    method: ["GET","HEAD"],
    types: {} as UsersIdGetHead,
  },
  {
    params: ["id"],
    name: 'users.edit',
    path: '/users/:id/edit',
    method: ["GET","HEAD"],
    types: {} as UsersIdEditGetHead,
  },
  {
    params: ["id"],
    name: 'users.update',
    path: '/users/:id',
    method: ["PUT","PATCH"],
    types: {} as UsersIdPutPatch,
  },
  {
    params: ["id"],
    name: 'users.destroy',
    path: '/users/:id',
    method: ["DELETE"],
    types: {} as UsersIdDelete,
  },
  {
    params: [],
    name: 'profile_webauthn.index',
    path: '/profile/webauthn',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: 'profile_webauthn.store',
    path: '/profile/webauthn',
    method: ["POST"],
    types: {} as ProfileWebauthnPost,
  },
  {
    params: ["id"],
    name: 'profile_webauthn.show',
    path: '/profile/webauthn/:id',
    method: ["GET","HEAD"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: 'profile_webauthn.update',
    path: '/profile/webauthn/:id',
    method: ["PUT","PATCH"],
    types: {} as unknown,
  },
  {
    params: ["id"],
    name: 'profile_webauthn.destroy',
    path: '/profile/webauthn/:id',
    method: ["DELETE"],
    types: {} as ProfileWebauthnIdDelete,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
